# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 4034f19b442cff7ac3037606db1b8d9a2958e5708b3243a7d98a86c4faf22c50891d7d726d1fc4ef81f3ab947e1f404a690100c6f36adcdf75734d0c8e8a21cd

test:
  secret_key_base: 00f3f2a0ca5f11fe1408c91a6653c5ff8ddbc49453d6c65feb8c6809a17f1fe3ede69f292f2a5b2b1ba8304a18eac8566c020ce5bb72fa4c6282c76469b713e3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
